version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - loomi_network
    restart: unless-stopped

  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "4000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - loomi_network
    restart: unless-stopped

networks:
  loomi_network:
    external: true 
  